name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push image
        run: |
          docker build -t swapi .
          docker tag swapi-lambda:latest 134087896061.dkr.ecr.us-east-1.amazonaws.com/swapi-lambda:latest
          docker push 134087896061.dkr.ecr.us-east-1.amazonaws.com/swapi-lambda:latest

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name swapi-function \
            --image-uri 134087896061.dkr.ecr.us-east-1.amazonaws.com/swapi-lambda:latest \
            --region us-east-1